---
collaborators:
  - username: fatsnorlax
    permission: admin
  - username: josefleventon
    permission: maintain
  - username: SmilySpilly
    permission: maintain
  - username: REGEX777
    permission: maintain