---
name: CompressImages

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  push:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.PAT }}
          compressOnly: ${{ github.event_name != 'pull_request' }}
      - name: Create Pull Request
        if: |
          github.event_name != 'pull_request' &&
          steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore: compress images'
          commit-message: 'chore: compress images'
          body: ${{ steps.calibre.outputs.markdown }}
